export enum DatePart {
	century = 'century',
	decade = 'decade',
	year = 'year',
	month = 'month',
	day = 'day',
	hour = 'hour',
	minute = 'minute',
	second = 'second',
	microseconds = 'microseconds',
	milliseconds = 'milliseconds',
	dow = 'dow',
	doy = 'doy',
	epoch = 'epoch',
	isodow = 'isodow',
	isoyear = 'isoyear',
	timezone = 'timezone',
	timezone_hour = 'timezone_hour',
	timezone_minute = 'timezone_minute'
}
