export enum PurchaseStatus {
	CANCELLED = 'CANCELLED',
	RECEIVED  = 'RECEIVED',
	ISSUES    = 'ISSUES',
	CONFIRMED = 'CONFIRMED',
	DECLINED  = 'DECLINED',
	STANDING  = 'STANDING',
	VIEWED    = 'VIEWED',
	SENT      = 'SENT',
	DRAFT     = 'DRAFT',
}
