name: Update Dependencies
on:
   schedule:
      -  cron: '0 0 * * *'
   workflow_dispatch:
jobs:
   update:
      runs-on: ubuntu-latest
      steps:
         -  name: checkout
            uses: actions/checkout@v3
         -  name: upgrade
            run: |
               yarn up '*'
               yarn up '@*/*'
               CHANGED=$(git diff package.json)
               if [ ! -z "$CHANGED" ]
               then
                  echo "changed=true" >> $GITHUB_ENV
                  yarn version patch
               fi
         -  name: create pull request
            uses: peter-evans/create-pull-request@v4
            if: ${{ env.changed }}
            with:
               commit-message: Update all dependencies
               branch: automatic_dependency_updates
               title: Update all Dependencies
               body: An automatic update of all dependencies.
               delete-branch: true
